### ISSUE TITLE
android hook向您请教

### ISSUE THREAD

**Issue by helei112g** [bigsinger/fakegps#1]
您好，看到很多你分享的android hook知识，想跟您请教几个问题(有偿)，不知是否方便留个联系方式？

dayugog@gmail.com 我的邮箱，微信：helei543345

**Comment by helei112g** [comment]
主要是想咨询，如果我开发一个应用，类似：叉叉加速器这种东西，如何实现，不安装 xposed，就实现hook功能？

因为像叉叉加速器他们就没有安装 xposed apk，依然实现了这部分功能。

**Comment by bigsinger** [comment]
可以逆向叉叉加速器

**Comment by helei112g** [comment]
因为是初次接触，不是特别明白

主要是想知道：利用 `xposed` 或者 `Cydia` 如何才能实现不用安装它们的apk，就能使用他们的功能呢？

因为逆向的话，只能看到实现逻辑，我不能分析出他们怎么怎么实现这一步的。已完整看完你的教程。
