### ISSUE TITLE
高版本支持

### ISSUE THREAD

**Issue by finzaghi9** [bigsinger/fakegps#11]
目前使用三星S3测试,在基于MIUI7、CYMOD11、三星原版系统三个Android4.4的系统都可以正常使用,测试app为高德地图. fakegps 版本1.3

刷了flyme6、LINEAGE OS14、MIUI8三个基于Android7.1的系统后出现几个现象:
1、在Xposed中激活模块并重启手机,就无法进入系统,反复重启,从日志打印看是来自getLastKnownLocationHooker 的 回调未作实现, 应该返回 Location类型, 代码只返回了 String类型,数据类型不匹配导致系统崩溃. 完善了这部分代码后可以进入系统.
2、高德地图刚进入是可以定位到模拟坐标的,但是一两秒更新后立刻返回到真实的坐标
3、系统设置中显示的的Wi-Fi SSID等信息也是显示的正确的真实信息,而不是像4.4上的模拟信息.

所以猜测高版本Android是不是增加了定位相关接口或者是更换了数据刷新机制导致fakegps无法在高版本上正常运行.

另外我更喜欢1.3及之前版本的点击或长按更新坐标的操作,1.4默认使用高德地图,点击后弹出地址列表会经常很茫然不知道选哪个地址,毕竟用户很多时候操作是基于地图图像的,对某个点周围详细的信息不一定了解.

希望作者的软件越来越好用^_^

**Comment by bigsinger** [comment]
@finzaghi9 1.3百度地图有效吗？我这边打开百度地图加载不出来。
后期计划是多配置几个地图选择器，还有谷歌的。这样用户可以自由选择地图选择器。
这个是加班写的，没时间打磨，先以能用为主，后面考虑慢慢完善。

**Comment by bigsinger** [comment]
@finzaghi9 Android7.0的需要安装另一套xposed，你有时间开发吗？给你开个协作？

**Comment by finzaghi9** [comment]
@bigsinger  很久没用了,我记得1.3的百度地图是可以用的,主要是系统版本变动带来了兼容问题, 另外xposed 我是从它的官网下的,都是下载对应Android版本匹配的xposed版本(版本如果不匹配xposed也不让装框架),我对Android系统的定位机制不是很了解.
