### ISSUE TITLE
地图显示有偏差，请问是火星坐标造成的吗？

### ISSUE THREAD

**Issue by chinawiz** [bigsinger/fakegps#2]
在使用内置地图取得GPS坐标后，放到高德地图里的位置和软件内位置有偏差，请问是什么原因？纠正这个错误，我能做些什么？

**Comment by bigsinger** [comment]
需要把百度坐标转换为GPS坐标，请升级到v1.2版本

**Comment by 1688pc** [comment]
@bigsinger 终于找到你了，酷安基佬欢迎您上架酷安。

**Comment by luchao1914** [comment]
微信定位并没有修改成功，想看着你的来做高德的运动轨迹
