### ISSUE TITLE
VirtualXpose中的企业微信不能加载1.7版本的指定位置。。。1.6版本使用正常。

### ISSUE THREAD

**Issue by philips805** [bigsinger/fakegps#23]
手机型号：Meizu 16s
Android版本：9
版本号：Flyme 7.3..0.1A

但系统强制提示升级1.7.。。。。。所以目前用不了了。

**Comment by philips805** [comment]
感谢@rolends1986
使用该版本能解决VirtualXpose（0.17.3）中的企业微信（2.8.2）不能加载1.7版本的指定位置问题。
https://raw.githubusercontent.com/bigsinger/fakegps/master/release/1.7.1.apk

**Comment by rolends1986** [comment]
@philips805 已发布新版本,我现在关闭了,有其他问题请再次open
