### ISSUE TITLE
好像没效果 

### ISSUE THREAD

**Issue by answer1874** [bigsinger/fakegps#25]
装的是1.7的版本 已经提示了地图已经刷新 打开百度地图 一点效果都没

**Comment by rolends1986** [comment]
@answer1874 百度地图目前无法hook到
参照这个issue，目前还没有RoadMap
https://github.com/bigsinger/fakegps/issues/16

**Comment by rolends1986** [comment]
高德地图没问题，建议使用高德

**Comment by answer1874** [comment]
原来如此  我看到有的用root的方案也做得很好 老哥有研究那个吗

**Comment by rolends1986** [comment]
作者可能有计划用substrate重新实现，抛弃xposed框架，有待
@bigsinger 跟进

**Comment by answer1874** [comment]
好的 期待
